/**
 * ProfileForge AI - 핵심 50개 컨셉 + 프롬프트 시드 라이브러리
 * PRD의 300개 시드 중 대표적 50개를 추출/정제.
 * 모든 프롬프트는 identity-lock 문장을 포함한다.
 */

export type RiskLevel = 'safe' | 'notice' | 'restricted'

export type ConceptCategory =
  | 'Professional'
  | 'Social'
  | 'ID-style'
  | 'Editorial'
  | 'Creator'
  | 'Cosplay'
  | 'Fantasy'
  | 'Sci-Fi'
  | 'Art/Avatar'

export interface Concept {
  id: string
  category: ConceptCategory
  name: string
  description: string
  useCase: string
  notRecommendedFor?: string
  riskLevel: RiskLevel
  /** 시각적 스타일 키워드 (UI 배지/요약용) */
  styleTags: string[]
  /** 의상 */
  outfit: string
  /** 배경 */
  background: string
  /** 조명 */
  lighting: string
  /** 표정 */
  expression: string
  /** 기본 출력 비율 */
  defaultAspect: '1:1' | '4:5' | '3:4' | '16:9'
  /** 권장 구도 */
  composition?: 'headshot' | 'half-body' | 'three-quarter' | 'full-body'
  /** IP/레퍼런스 정책 */
  inspirationPolicy?: 'original' | 'inspired-original' | 'restricted-reference'
  /** 예상 생성 복잡도 */
  estimatedComplexity?: 'standard' | 'complex' | 'very-complex'
  /** 창의성 기본값 (0=보수적, 50=균형, 100=창의적) */
  defaultCreativity: number
  /** AI 생성 카드 썸네일용 프롬프트 (카테고리 대표 이미지 생성용) */
  thumbnailPrompt: string
  /** 완성 프롬프트 시드 (사용자 선택 항목으로 치환됨) */
  promptSeed: string
  /** 카드에 표시할 크레딧 비용 */
  creditCost: number
}

const IDENTITY_LOCK =
  'Use the uploaded image as the only face and identity reference. Preserve the same person, facial structure, age range, skin tone, hairline, and distinctive features while'

const COMMON_TAIL =
  'Create a new profile image with clear eyes, natural skin texture, high-resolution realistic quality, and a composition suitable for the selected aspect ratio. Avoid watermark, text, logo, face distortion, over-retouching, and copying the source photo pose.'

const buildSeed = (_useCase: string, name: string, style: string) =>
  `${IDENTITY_LOCK} creating a '${name}' profile portrait. Style: ${style}. ${COMMON_TAIL}`

const buildThumb = (style: string) =>
  `professional profile photo sample, ${style}, head and shoulders, studio photography, high quality, no text, no watermark`

export const CONCEPTS: Concept[] = [
  // === Professional (8) ===
  {
    id: 'pro-corporate-navy',
    category: 'Professional',
    name: 'Classic Corporate Navy',
    description: '이력서/채용/비즈니스에 신뢰를 주는 네이비 정장 프로필',
    useCase: '이력서, LinkedIn, 회사 프로필',
    riskLevel: 'safe',
    styleTags: ['네이비 정장', '스튜디오', '부드러운 조명'],
    outfit: 'navy suit, white shirt',
    background: 'light gray studio',
    lighting: 'softbox lighting',
    expression: 'confident smile',
    defaultAspect: '4:5',
    defaultCreativity: 20,
    thumbnailPrompt: buildThumb('navy suit, white shirt, light gray studio, softbox lighting, confident smile'),
    promptSeed: buildSeed('이력서/채용/비즈니스', 'Classic Corporate Navy', 'navy suit, white shirt, light gray studio, softbox lighting, confident smile'),
    creditCost: 2,
  },
  {
    id: 'pro-black-blazer',
    category: 'Professional',
    name: 'Corporate Black Blazer',
    description: '깔끔한 화이트 배경의 블랙 블레이저 프로필',
    useCase: 'LinkedIn, 회사 소개 페이지',
    riskLevel: 'safe',
    styleTags: ['블랙 블레이저', '화이트 배경', '직접 응시'],
    outfit: 'tailored black blazer',
    background: 'clean white background',
    lighting: 'even soft light',
    expression: 'friendly direct eye contact',
    defaultAspect: '1:1',
    defaultCreativity: 20,
    thumbnailPrompt: buildThumb('black blazer, white background, friendly direct eye contact'),
    promptSeed: buildSeed('이력서/채용/비즈니스', 'Corporate Black Blazer', 'tailored black blazer, clean white background, friendly direct eye contact'),
    creditCost: 2,
  },
  {
    id: 'pro-executive-dark',
    category: 'Professional',
    name: 'Executive Dark Studio',
    description: '차콜 수트와 드라마틱 사이드 조명의 임원용 프로필',
    useCase: 'C-level 프로필, 강연 소개',
    riskLevel: 'safe',
    styleTags: ['차콜 수트', '어두운 배경', '드라마틱 조명'],
    outfit: 'charcoal suit',
    background: 'dark textured backdrop',
    lighting: 'dramatic side light',
    expression: 'calm authority',
    defaultAspect: '4:5',
    defaultCreativity: 25,
    thumbnailPrompt: buildThumb('charcoal suit, dark textured backdrop, dramatic side light, calm authority'),
    promptSeed: buildSeed('이력서/채용/비즈니스', 'Executive Dark Studio', 'charcoal suit, dark textured backdrop, dramatic side light, calm authority'),
    creditCost: 2,
  },
  {
    id: 'pro-founder-pr',
    category: 'Professional',
    name: 'Founder PR Portrait',
    description: '현대 오피스 보케와 자신감 있는 표정의 창업자 포트레이트',
    useCase: '창업자 PR, 투자 자료, 언론 인터뷰',
    riskLevel: 'safe',
    styleTags: ['스마트 블레이저', '오피스 보케', '자신감'],
    outfit: 'smart blazer',
    background: 'modern office bokeh',
    lighting: 'natural window light',
    expression: 'direct confident expression',
    defaultAspect: '4:5',
    defaultCreativity: 30,
    thumbnailPrompt: buildThumb('smart blazer, modern office bokeh, direct confident expression'),
    promptSeed: buildSeed('이력서/채용/비즈니스', 'Founder PR Portrait', 'smart blazer, modern office bokeh, direct confident expression'),
    creditCost: 2,
  },
  {
    id: 'pro-startup-casual',
    category: 'Professional',
    name: 'Startup Casual',
    description: '캐주얼하면서도 단정한 스타트업 분위기의 프로필',
    useCase: '스타트업 팀 페이지, GitHub 프로필',
    riskLevel: 'safe',
    styleTags: ['캐주얼 셔츠', '밝은 오피스', '자연스러운 미소'],
    outfit: 'casual button-up shirt',
    background: 'bright startup office',
    lighting: 'natural daylight',
    expression: 'natural relaxed smile',
    defaultAspect: '1:1',
    defaultCreativity: 30,
    thumbnailPrompt: buildThumb('casual button-up shirt, bright startup office, natural relaxed smile'),
    promptSeed: buildSeed('이력서/채용/비즈니스', 'Startup Casual', 'casual button-up shirt, bright startup office, natural relaxed smile'),
    creditCost: 2,
  },
  {
    id: 'pro-minimal-white',
    category: 'Professional',
    name: 'Minimal White',
    description: '여백이 많은 화이트 배경의 미니멀 프로필',
    useCase: '포트폴리오, 디자이너 프로필',
    riskLevel: 'safe',
    styleTags: ['미니멀', '화이트', '깔끔함'],
    outfit: 'minimal neutral top',
    background: 'pure white seamless',
    lighting: 'soft even light',
    expression: 'calm neutral expression',
    defaultAspect: '1:1',
    defaultCreativity: 20,
    thumbnailPrompt: buildThumb('minimal neutral top, pure white seamless, soft even light, calm neutral expression'),
    promptSeed: buildSeed('이력서/채용/비즈니스', 'Minimal White', 'minimal neutral top, pure white seamless, soft even light, calm neutral expression'),
    creditCost: 2,
  },
  {
    id: 'pro-linkedin-keynote',
    category: 'Professional',
    name: 'LinkedIn Keynote',
    description: '강연 무대를 연상시키는 자신감 있는 LinkedIn 프로필',
    useCase: 'LinkedIn 헤드라인, 강연자 소개',
    riskLevel: 'safe',
    styleTags: ['강연 무드', '따뜻한 스팟라이트', '에너지'],
    outfit: 'keynote blazer',
    background: 'soft stage bokeh',
    lighting: 'warm spotlight',
    expression: 'energetic confident smile',
    defaultAspect: '1:1',
    defaultCreativity: 35,
    thumbnailPrompt: buildThumb('keynote blazer, soft stage bokeh, warm spotlight, energetic confident smile'),
    promptSeed: buildSeed('이력서/채용/비즈니스', 'LinkedIn Keynote', 'keynote blazer, soft stage bokeh, warm spotlight, energetic confident smile'),
    creditCost: 2,
  },
  {
    id: 'pro-consultant-warm',
    category: 'Professional',
    name: 'Consultant Warm',
    description: '신뢰를 주는 따뜻한 컨설턴트 프로필',
    useCase: '컨설턴트, 자문위원 프로필',
    riskLevel: 'safe',
    styleTags: ['따뜻한 톤', '신뢰감', '자연스러운 미소'],
    outfit: 'navy blazer, open collar',
    background: 'warm office bokeh',
    lighting: 'warm key light',
    expression: 'trustworthy calm smile',
    defaultAspect: '4:5',
    defaultCreativity: 25,
    thumbnailPrompt: buildThumb('navy blazer open collar, warm office bokeh, warm key light, trustworthy calm smile'),
    promptSeed: buildSeed('이력서/채용/비즈니스', 'Consultant Warm', 'navy blazer, open collar, warm office bokeh, warm key light, trustworthy calm smile'),
    creditCost: 2,
  },

  // === Social / Lifestyle (6) ===
  {
    id: 'social-lifestyle-coffee',
    category: 'Social',
    name: 'Coffee Shop Lifestyle',
    description: '카페 보케와 따뜻한 자연광의 캐주얼 소셜 프로필',
    useCase: 'SNS 프로필, 블로그, 소개글',
    riskLevel: 'safe',
    styleTags: ['카페 보케', '캐주얼', '따뜻한 조명'],
    outfit: 'smart casual outfit',
    background: 'coffee shop bokeh',
    lighting: 'warm window light',
    expression: 'warm approachable look',
    defaultAspect: '1:1',
    defaultCreativity: 40,
    thumbnailPrompt: buildThumb('smart casual outfit, coffee shop bokeh, warm window light, warm approachable look'),
    promptSeed: buildSeed('소셜/캐주얼', 'Coffee Shop Lifestyle', 'smart casual outfit, coffee shop bokeh, warm window light, warm approachable look'),
    creditCost: 2,
  },
  {
    id: 'social-outdoor-nature',
    category: 'Social',
    name: 'Outdoor Nature',
    description: '자연광과 풍경 보케가 어우러진 아웃도어 프로필',
    useCase: 'SNS, 취미 커뮤니티',
    riskLevel: 'safe',
    styleTags: ['자연광', '아웃도어', '캐주얼'],
    outfit: 'outdoor casual jacket',
    background: 'green nature bokeh',
    lighting: 'soft daylight',
    expression: 'relaxed candid smile',
    defaultAspect: '1:1',
    defaultCreativity: 45,
    thumbnailPrompt: buildThumb('outdoor casual jacket, green nature bokeh, soft daylight, relaxed candid smile'),
    promptSeed: buildSeed('소셜/캐주얼', 'Outdoor Nature', 'outdoor casual jacket, green nature bokeh, soft daylight, relaxed candid smile'),
    creditCost: 2,
  },
  {
    id: 'social-autumn-city',
    category: 'Social',
    name: 'Autumn City',
    description: '가을 도시 보케와 코트, 머플러의 시네마틱 프로필',
    useCase: 'SNS, 인스타그램 프로필',
    riskLevel: 'safe',
    styleTags: ['가을 무드', '코트+머플러', '시네마틱'],
    outfit: 'coat and scarf',
    background: 'autumn street bokeh',
    lighting: 'warm cinematic light',
    expression: 'serene warm expression',
    defaultAspect: '4:5',
    defaultCreativity: 50,
    thumbnailPrompt: buildThumb('coat and scarf, autumn street bokeh, warm cinematic light, serene warm expression'),
    promptSeed: buildSeed('소셜/캐주얼', 'Autumn City', 'coat and scarf, autumn street bokeh, warm cinematic light'),
    creditCost: 2,
  },
  {
    id: 'social-night-market',
    category: 'Social',
    name: 'Night Market Portrait',
    description: '야간 시장 보케와 따뜻한 조명의 무드 프로필',
    useCase: 'SNS 프로필, 데이트 앱',
    riskLevel: 'safe',
    styleTags: ['야간 보케', '따뜻한 조명', '캔디드'],
    outfit: 'stylish casual',
    background: 'night market bokeh',
    lighting: 'warm market lights',
    expression: 'candid polished face',
    defaultAspect: '1:1',
    defaultCreativity: 55,
    thumbnailPrompt: buildThumb('stylish casual, night market bokeh, warm market lights, candid polished face'),
    promptSeed: buildSeed('소셜/캐주얼', 'Night Market Portrait', 'tasteful night market bokeh, warm lights, candid polished face'),
    creditCost: 2,
  },
  {
    id: 'social-beach-summer',
    category: 'Social',
    name: 'Beach Summer',
    description: '여름 해변의 밝고 자연스러운 소셜 프로필',
    useCase: 'SNS, 여행 블로그',
    riskLevel: 'safe',
    styleTags: ['해변', '여름 무드', '밝은 미소'],
    outfit: 'linen shirt',
    background: 'beach and ocean bokeh',
    lighting: 'bright natural sunlight',
    expression: 'bright relaxed smile',
    defaultAspect: '1:1',
    defaultCreativity: 50,
    thumbnailPrompt: buildThumb('linen shirt, beach and ocean bokeh, bright natural sunlight, bright relaxed smile'),
    promptSeed: buildSeed('소셜/캐주얼', 'Beach Summer', 'linen shirt, beach and ocean bokeh, bright natural sunlight, bright relaxed smile'),
    creditCost: 2,
  },
  {
    id: 'social-gallery-opening',
    category: 'Social',
    name: 'Gallery Opening',
    description: '아트 갤러리 배경의 세련된 소셜 프로필',
    useCase: 'SNS, 아트 커뮤니티',
    riskLevel: 'safe',
    styleTags: ['갤러리 배경', '블랙 오프닝', '세련됨'],
    outfit: 'black outfit',
    background: 'art gallery background',
    lighting: 'gallery soft light',
    expression: 'refined creative expression',
    defaultAspect: '4:5',
    defaultCreativity: 55,
    thumbnailPrompt: buildThumb('black outfit, art gallery background, gallery soft light, refined creative expression'),
    promptSeed: buildSeed('소셜/캐주얼', 'Gallery Opening', 'art gallery background, black outfit, refined creative expression'),
    creditCost: 2,
  },

  // === ID-style (4) ===
  {
    id: 'id-passport-style',
    category: 'ID-style',
    name: 'Passport-style Unofficial',
    description: '여권/증명사진 스타일의 화이트 배경 프로필. 공식 제출용이 아님.',
    useCase: '비공식 참고용, 연습용 증명사진',
    notRecommendedFor: '공식 여권, 비자, 주민등록증, 운전면허증 제출',
    riskLevel: 'notice',
    styleTags: ['화이트 배경', '정면', '규격'],
    outfit: 'dark solid top',
    background: 'plain white background',
    lighting: 'even flat front light',
    expression: 'neutral expression, mouth closed',
    defaultAspect: '3:4',
    defaultCreativity: 10,
    thumbnailPrompt: buildThumb('dark solid top, plain white background, even flat front light, neutral expression, passport style'),
    promptSeed: buildSeed('비공식 증명사진 스타일 참고용', 'Passport-style Unofficial', 'dark solid top, plain white background, even flat front light, neutral expression, mouth closed'),
    creditCost: 2,
  },
  {
    id: 'id-badge-corporate',
    category: 'ID-style',
    name: 'ID Badge Corporate',
    description: '사원증/출입증 스타일의 단정한 화이트 배경 프로필',
    useCase: '사내 디렉토리, 출입증 사진 (비공식)',
    notRecommendedFor: '공식 신분증 제출',
    riskLevel: 'notice',
    styleTags: ['화이트 배경', '단정함', '정면'],
    outfit: 'corporate polo or shirt',
    background: 'plain white wall',
    lighting: 'even soft light',
    expression: 'friendly neutral smile',
    defaultAspect: '3:4',
    defaultCreativity: 15,
    thumbnailPrompt: buildThumb('corporate polo, plain white wall, even soft light, friendly neutral smile'),
    promptSeed: buildSeed('비공식 사원증 스타일 참고용', 'ID Badge Corporate', 'corporate polo or shirt, plain white wall, even soft light, friendly neutral smile'),
    creditCost: 2,
  },
  {
    id: 'id-school-portrait',
    category: 'ID-style',
    name: 'School Portrait Style',
    description: '졸업앨범/학교 사진 스타일의 단정한 프로필',
    useCase: '졸업앨범 스타일 참고, 비공식 용도',
    riskLevel: 'notice',
    styleTags: ['졸업앨범 무드', '단정함', '부드러운 조명'],
    outfit: 'clean shirt or uniform',
    background: 'soft gradient backdrop',
    lighting: 'soft school portrait light',
    expression: 'gentle smile',
    defaultAspect: '3:4',
    defaultCreativity: 15,
    thumbnailPrompt: buildThumb('clean shirt, soft gradient backdrop, soft school portrait light, gentle smile'),
    promptSeed: buildSeed('비공식 졸업앨범 스타일', 'School Portrait Style', 'clean shirt or uniform, soft gradient backdrop, soft school portrait light, gentle smile'),
    creditCost: 2,
  },
  {
    id: 'id-resume-clean',
    category: 'ID-style',
    name: 'Resume Clean',
    description: '이력서용으로 가장 널리 쓰이는 깔끔한 화이트 배경 프로필',
    useCase: '이력서, 지원서',
    riskLevel: 'safe',
    styleTags: ['화이트 배경', '이력서용', '깔끔함'],
    outfit: 'solid color top',
    background: 'pure white',
    lighting: 'flat even light',
    expression: 'soft confident smile',
    defaultAspect: '3:4',
    defaultCreativity: 15,
    thumbnailPrompt: buildThumb('solid color top, pure white, flat even light, soft confident smile'),
    promptSeed: buildSeed('이력서/지원서', 'Resume Clean', 'solid color top, pure white, flat even light, soft confident smile'),
    creditCost: 2,
  },

  // === Editorial (5) ===
  {
    id: 'editorial-magazine-cover',
    category: 'Editorial',
    name: 'Magazine Cover',
    description: '잡지 표지를 연상시키는 강렬한 에디토리얼 포트레이트',
    useCase: '매거진, 인터뷰 표지, 아트 프로젝트',
    riskLevel: 'safe',
    styleTags: ['매거진', '강렬한 조명', '하이패션'],
    outfit: 'statement designer outfit',
    background: 'editorial seamless',
    lighting: 'dramatic fashion lighting',
    expression: 'strong editorial gaze',
    defaultAspect: '4:5',
    defaultCreativity: 70,
    thumbnailPrompt: buildThumb('statement designer outfit, editorial seamless, dramatic fashion lighting, strong editorial gaze, magazine cover style'),
    promptSeed: buildSeed('에디토리얼/매거진', 'Magazine Cover', 'statement designer outfit, editorial seamless, dramatic fashion lighting, strong editorial gaze'),
    creditCost: 3,
  },
  {
    id: 'editorial-mono-noir',
    category: 'Editorial',
    name: 'Monochrome Noir',
    description: '흑백 필름 느낌의 누아르 에디토리얼 포트레이트',
    useCase: '아트 포트폴리오, 프로필 사진',
    riskLevel: 'safe',
    styleTags: ['흑백', '누아르', '필름 무드'],
    outfit: 'black turtleneck',
    background: 'deep shadow background',
    lighting: 'single rim light',
    expression: 'contemplative gaze',
    defaultAspect: '4:5',
    defaultCreativity: 65,
    thumbnailPrompt: buildThumb('black turtleneck, deep shadow background, single rim light, contemplative gaze, monochrome noir film style'),
    promptSeed: buildSeed('에디토리얼/흑백', 'Monochrome Noir', 'black turtleneck, deep shadow background, single rim light, contemplative gaze, monochrome film grain'),
    creditCost: 3,
  },
  {
    id: 'editorial-beauty-closeup',
    category: 'Editorial',
    name: 'Beauty Closeup',
    description: '뷰티 에디토리얼 클로즈업 프로필',
    useCase: '뷰티 포트폴리오, SNS',
    riskLevel: 'safe',
    styleTags: ['뷰티', '클로즈업', '글로우'],
    outfit: 'minimal beauty look',
    background: 'soft pastel backdrop',
    lighting: 'beauty ring light',
    expression: 'serene beauty gaze',
    defaultAspect: '4:5',
    defaultCreativity: 60,
    thumbnailPrompt: buildThumb('minimal beauty look, soft pastel backdrop, beauty ring light, serene beauty gaze, beauty editorial closeup'),
    promptSeed: buildSeed('에디토리얼/뷰티', 'Beauty Closeup', 'minimal beauty look, soft pastel backdrop, beauty ring light, serene beauty gaze'),
    creditCost: 3,
  },
  {
    id: 'editorial-cinematic-warm',
    category: 'Editorial',
    name: 'Cinematic Warm',
    description: '따뜻한 시네마틱 톤의 영화적 포트레이트',
    useCase: '영화 포스터 스타일, 아트',
    riskLevel: 'safe',
    styleTags: ['시네마틱', '따뜻한 톤', '영화적'],
    outfit: 'knit sweater',
    background: 'warm cinematic interior',
    lighting: 'golden hour rim light',
    expression: 'cinematic introspective look',
    defaultAspect: '4:5',
    defaultCreativity: 65,
    thumbnailPrompt: buildThumb('knit sweater, warm cinematic interior, golden hour rim light, cinematic introspective look'),
    promptSeed: buildSeed('에디토리얼/시네마틱', 'Cinematic Warm', 'knit sweater, warm cinematic interior, golden hour rim light, cinematic introspective look'),
    creditCost: 3,
  },
  {
    id: 'editorial-vogue-style',
    category: 'Editorial',
    name: 'Vogue Style Editorial',
    description: '보그 스타일의 하이패션 에디토리얼 포트레이트',
    useCase: '패션 포트폴리오, 아트',
    riskLevel: 'safe',
    styleTags: ['하이패션', '보그 스타일', '강렬함'],
    outfit: 'avant-garde fashion',
    background: 'studio cyclorama',
    lighting: 'high fashion hard light',
    expression: 'fierce editorial look',
    defaultAspect: '4:5',
    defaultCreativity: 75,
    thumbnailPrompt: buildThumb('avant-garde fashion, studio cyclorama, high fashion hard light, fierce editorial look, vogue style'),
    promptSeed: buildSeed('에디토리얼/하이패션', 'Vogue Style Editorial', 'avant-garde fashion, studio cyclorama, high fashion hard light, fierce editorial look'),
    creditCost: 3,
  },

  // === Creator / Influencer (6) ===
  {
    id: 'creator-neon-glow',
    category: 'Creator',
    name: 'Neon Glow Creator',
    description: '네온 사인 글로우가 어우러진 크리에이터 프로필',
    useCase: '유튜브 썸네일, 트위치 프로필',
    riskLevel: 'safe',
    styleTags: ['네온', '사이버 무드', '글로우'],
    outfit: 'streetwear hoodie',
    background: 'neon city night',
    lighting: 'pink and cyan neon glow',
    expression: 'cool creator expression',
    defaultAspect: '1:1',
    defaultCreativity: 75,
    thumbnailPrompt: buildThumb('streetwear hoodie, neon city night, pink and cyan neon glow, cool creator expression'),
    promptSeed: buildSeed('크리에이터/인플루언서', 'Neon Glow Creator', 'streetwear hoodie, neon city night, pink and cyan neon glow, cool creator expression'),
    creditCost: 3,
  },
  {
    id: 'creator-gaming-streamer',
    category: 'Creator',
    name: 'Gaming Streamer',
    description: '게이밍 RGB 조명의 스트리머 프로필',
    useCase: '트위치, 유튜브 게임 채널',
    riskLevel: 'safe',
    styleTags: ['RGB', '게이밍', '스트리머'],
    outfit: 'gaming esports jersey',
    background: 'gaming setup bokeh',
    lighting: 'RGB LED ambient',
    expression: 'energetic gaming smile',
    defaultAspect: '1:1',
    defaultCreativity: 70,
    thumbnailPrompt: buildThumb('gaming esports jersey, gaming setup bokeh, RGB LED ambient, energetic gaming smile'),
    promptSeed: buildSeed('크리에이터/인플루언서', 'Gaming Streamer', 'gaming esports jersey, gaming setup bokeh, RGB LED ambient, energetic gaming smile'),
    creditCost: 3,
  },
  {
    id: 'creator-home-studio',
    category: 'Creator',
    name: 'Home Studio Creator',
    description: '홈 스튜디오 배경의 자연스러운 크리에이터 프로필',
    useCase: '유튜버, 팟캐스터 프로필',
    riskLevel: 'safe',
    styleTags: ['홈 스튜디오', '부드러운 조명', '자연스러움'],
    outfit: 'casual creator wear',
    background: 'clean home studio setup',
    lighting: 'soft key light',
    expression: 'authentic creator mood',
    defaultAspect: '1:1',
    defaultCreativity: 50,
    thumbnailPrompt: buildThumb('casual creator wear, clean home studio setup, soft key light, authentic creator mood'),
    promptSeed: buildSeed('크리에이터/인플루언서', 'Home Studio Creator', 'clean home studio setup, soft key light, authentic creator mood'),
    creditCost: 2,
  },
  {
    id: 'creator-podcast-host',
    category: 'Creator',
    name: 'Podcast Host',
    description: '마이크가 있는 팟캐스트 호스트 프로필',
    useCase: '팟캐스트 커버, 오디오 채널',
    riskLevel: 'safe',
    styleTags: ['마이크', '팟캐스트', '따뜻한 톤'],
    outfit: 'smart casual',
    background: 'podcast studio warm',
    lighting: 'warm studio light',
    expression: 'engaging conversational smile',
    defaultAspect: '1:1',
    defaultCreativity: 55,
    thumbnailPrompt: buildThumb('smart casual, podcast studio warm, warm studio light, engaging conversational smile'),
    promptSeed: buildSeed('크리에이터/인플루언서', 'Podcast Host', 'smart casual, podcast studio warm, warm studio light, engaging conversational smile'),
    creditCost: 3,
  },
  {
    id: 'creator-fitness-coach',
    category: 'Creator',
    name: 'Fitness Coach',
    description: '피트니스 코치 풍의 에너지 넘치는 프로필',
    useCase: '피트니스 SNS, 코치 프로필',
    riskLevel: 'safe',
    styleTags: ['피트니스', '에너지', '건강'],
    outfit: 'athletic workout wear',
    background: 'gym bokeh',
    lighting: 'bright athletic light',
    expression: 'healthy energetic smile',
    defaultAspect: '1:1',
    defaultCreativity: 55,
    thumbnailPrompt: buildThumb('athletic workout wear, gym bokeh, bright athletic light, healthy energetic smile'),
    promptSeed: buildSeed('크리에이터/인플루언서', 'Fitness Coach', 'athletic workout wear, gym bokeh, bright athletic light, healthy energetic smile'),
    creditCost: 3,
  },
  {
    id: 'creator-food-blogger',
    category: 'Creator',
    name: 'Food Blogger',
    description: '레스토랑 보케의 따뜻한 푸드 블로거 프로필',
    useCase: '푸드 블로그, SNS',
    riskLevel: 'safe',
    styleTags: ['레스토랑 보케', '따뜻한 조명', '친근함'],
    outfit: 'casual chic',
    background: 'restaurant warm bokeh',
    lighting: 'warm restaurant light',
    expression: 'delighted warm smile',
    defaultAspect: '1:1',
    defaultCreativity: 55,
    thumbnailPrompt: buildThumb('casual chic, restaurant warm bokeh, warm restaurant light, delighted warm smile'),
    promptSeed: buildSeed('크리에이터/인플루언서', 'Food Blogger', 'casual chic, restaurant warm bokeh, warm restaurant light, delighted warm smile'),
    creditCost: 3,
  },

  // === Cosplay / Character (5) ===
  {
    id: 'cosplay-anime-hero',
    category: 'Cosplay',
    name: 'Anime Hero (Inspired Original)',
    description: '애니메이션 영웅 컨셉의 영감을 받은 오리지널 코스프레 프로필',
    useCase: '코스프레 커뮤니티, SNS',
    notRecommendedFor: '특정 상업 IP 그대로 복제',
    riskLevel: 'notice',
    styleTags: ['애니메이션', '영웅', '코스프레'],
    outfit: 'original anime-inspired hero costume',
    background: 'anime sky backdrop',
    lighting: 'cel-shaded style light',
    expression: 'determined hero expression',
    defaultAspect: '1:1',
    defaultCreativity: 85,
    thumbnailPrompt: buildThumb('original anime-inspired hero costume, anime sky backdrop, cel-shaded style light, determined hero expression'),
    promptSeed: buildSeed('코스프레/캐릭터 (오리지널 영감)', 'Anime Hero', 'original anime-inspired hero costume, anime sky backdrop, cel-shaded style light, determined hero expression'),
    creditCost: 4,
  },
  {
    id: 'cosplay-fantasy-mage',
    category: 'Cosplay',
    name: 'Fantasy Mage',
    description: '판타지 마법사 컨셉의 코스프레 프로필',
    useCase: '코스프레, 판타지 커뮤니티',
    riskLevel: 'safe',
    styleTags: ['판타지', '마법사', '로브'],
    outfit: 'mystic mage robe',
    background: 'enchanted forest',
    lighting: 'glowing magical light',
    expression: 'mysterious mage gaze',
    defaultAspect: '4:5',
    defaultCreativity: 85,
    thumbnailPrompt: buildThumb('mystic mage robe, enchanted forest, glowing magical light, mysterious mage gaze'),
    promptSeed: buildSeed('코스프레/판타지', 'Fantasy Mage', 'mystic mage robe, enchanted forest, glowing magical light, mysterious mage gaze'),
    creditCost: 4,
  },
  {
    id: 'cosplay-steampunk',
    category: 'Cosplay',
    name: 'Steampunk Explorer',
    description: '스팀펑크 탐험가 컨셉의 코스프레 프로필',
    useCase: '코스프레, 스팀펑크 커뮤니티',
    riskLevel: 'safe',
    styleTags: ['스팀펑크', '탐험가', '빈티지'],
    outfit: 'steampunk leather outfit with gears',
    background: 'brass workshop',
    lighting: 'warm gas lamp light',
    expression: 'curious explorer look',
    defaultAspect: '4:5',
    defaultCreativity: 85,
    thumbnailPrompt: buildThumb('steampunk leather outfit with gears, brass workshop, warm gas lamp light, curious explorer look'),
    promptSeed: buildSeed('코스프레/스팀펑크', 'Steampunk Explorer', 'steampunk leather outfit with gears, brass workshop, warm gas lamp light, curious explorer look'),
    creditCost: 4,
  },
  {
    id: 'cosplay-cyber-warrior',
    category: 'Cosplay',
    name: 'Cyber Warrior',
    description: '사이버 전사 컨셉의 테크 웨어 코스프레 프로필',
    useCase: '코스프레, 사이버punk 커뮤니티',
    riskLevel: 'safe',
    styleTags: ['사이버', '테크웨어', '네온'],
    outfit: 'techwear cyber armor',
    background: 'cyberpunk alley',
    lighting: 'neon magenta light',
    expression: 'intense cyber gaze',
    defaultAspect: '1:1',
    defaultCreativity: 85,
    thumbnailPrompt: buildThumb('techwear cyber armor, cyberpunk alley, neon magenta light, intense cyber gaze'),
    promptSeed: buildSeed('코스프레/사이버', 'Cyber Warrior', 'techwear cyber armor, cyberpunk alley, neon magenta light, intense cyber gaze'),
    creditCost: 4,
  },
  {
    id: 'cosplay-historical-noble',
    category: 'Cosplay',
    name: 'Historical Noble',
    description: '역사적 귀족 컨셉의 클래식 코스프레 프로필',
    useCase: '코스프레, 사극 커뮤니티',
    riskLevel: 'safe',
    styleTags: ['귀족', '클래식', '고풍'],
    outfit: 'historical noble attire',
    background: 'classic palace interior',
    lighting: 'painterly classic light',
    expression: 'refined noble expression',
    defaultAspect: '4:5',
    defaultCreativity: 80,
    thumbnailPrompt: buildThumb('historical noble attire, classic palace interior, painterly classic light, refined noble expression'),
    promptSeed: buildSeed('코스프레/역사', 'Historical Noble', 'historical noble attire, classic palace interior, painterly classic light, refined noble expression'),
    creditCost: 4,
  },

  // === Fantasy (6) ===
  {
    id: 'fantasy-knight',
    category: 'Fantasy',
    name: 'Fantasy Knight',
    description: '판타지 기사 컨셉의 영웅적 포트레이트',
    useCase: '판타지 커뮤니티, 게임 아바타',
    riskLevel: 'safe',
    styleTags: ['기사', '판타지', '갑옷'],
    outfit: 'ornate plate armor',
    background: 'castle hall',
    lighting: 'dramatic torchlight',
    expression: 'noble knight expression',
    defaultAspect: '4:5',
    defaultCreativity: 85,
    thumbnailPrompt: buildThumb('ornate plate armor, castle hall, dramatic torchlight, noble knight expression'),
    promptSeed: buildSeed('판타지', 'Fantasy Knight', 'ornate plate armor, castle hall, dramatic torchlight, noble knight expression'),
    creditCost: 4,
  },
  {
    id: 'fantasy-elf-archer',
    category: 'Fantasy',
    name: 'Elf Archer',
    description: '엘프 궁수 컨셉의 숲 속 판타지 포트레이트',
    useCase: '판타지 커뮤니티, 게임 아바타',
    riskLevel: 'safe',
    styleTags: ['엘프', '궁수', '숲'],
    outfit: 'elven leather armor',
    background: 'ancient forest',
    lighting: 'dappled forest light',
    expression: 'serene elven gaze',
    defaultAspect: '4:5',
    defaultCreativity: 85,
    thumbnailPrompt: buildThumb('elven leather armor, ancient forest, dappled forest light, serene elven gaze'),
    promptSeed: buildSeed('판타지', 'Elf Archer', 'elven leather armor, ancient forest, dappled forest light, serene elven gaze'),
    creditCost: 4,
  },
  {
    id: 'fantasy-kdrama-romantic',
    category: 'Fantasy',
    name: 'K-Drama Romantic',
    description: '한국 드라마 무드의 로맨틱 시네마틱 포트레이트',
    useCase: 'SNS, 팬 커뮤니티',
    riskLevel: 'safe',
    styleTags: ['K-드라마', '로맨틱', '시네마틱'],
    outfit: 'elegant modern hanbok-inspired',
    background: 'cherry blossom park',
    lighting: 'soft golden hour light',
    expression: 'warm romantic gaze',
    defaultAspect: '4:5',
    defaultCreativity: 70,
    thumbnailPrompt: buildThumb('elegant modern hanbok-inspired, cherry blossom park, soft golden hour light, warm romantic gaze'),
    promptSeed: buildSeed('판타지/로맨틱', 'K-Drama Romantic', 'elegant modern hanbok-inspired, cherry blossom park, soft golden hour light, warm romantic gaze'),
    creditCost: 4,
  },
  {
    id: 'fantasy-noir-detective',
    category: 'Fantasy',
    name: 'Noir Detective',
    description: '필름 누아르 탐정 컨셉의 무드 포트레이트',
    useCase: '취미, 아트 프로젝트',
    riskLevel: 'safe',
    styleTags: ['누아르', '탐정', '흑백'],
    outfit: 'trench coat and fedora',
    background: 'rainy noir street',
    lighting: 'single street lamp',
    expression: 'hardboiled detective look',
    defaultAspect: '4:5',
    defaultCreativity: 80,
    thumbnailPrompt: buildThumb('trench coat and fedora, rainy noir street, single street lamp, hardboiled detective look'),
    promptSeed: buildSeed('판타지/누아르', 'Noir Detective', 'trench coat and fedora, rainy noir street, single street lamp, hardboiled detective look'),
    creditCost: 4,
  },
  {
    id: 'fantasy-pirate-captain',
    category: 'Fantasy',
    name: 'Pirate Captain',
    description: '해적 선장 컨셉의 어드벤처 포트레이트',
    useCase: '판타지, 취미',
    riskLevel: 'safe',
    styleTags: ['해적', '어드벤처', '바다'],
    outfit: 'pirate captain coat',
    background: 'ship deck at sunset',
    lighting: 'dramatic sunset light',
    expression: 'bold captain expression',
    defaultAspect: '4:5',
    defaultCreativity: 85,
    thumbnailPrompt: buildThumb('pirate captain coat, ship deck at sunset, dramatic sunset light, bold captain expression'),
    promptSeed: buildSeed('판타지/어드벤처', 'Pirate Captain', 'pirate captain coat, ship deck at sunset, dramatic sunset light, bold captain expression'),
    creditCost: 4,
  },
  {
    id: 'fantasy-vintage-royal',
    category: 'Fantasy',
    name: 'Vintage Royal',
    description: '빈티지 왕실 컨셉의 클래식 로얄 포트레이트',
    useCase: '판타지, 아트',
    riskLevel: 'safe',
    styleTags: ['왕실', '클래식', '고풍'],
    outfit: 'royal vintage gown',
    background: 'ornate palace',
    lighting: 'painterly renaissance light',
    expression: 'regal composure',
    defaultAspect: '4:5',
    defaultCreativity: 80,
    thumbnailPrompt: buildThumb('royal vintage gown, ornate palace, painterly renaissance light, regal composure'),
    promptSeed: buildSeed('판타지/로얄', 'Vintage Royal', 'royal vintage gown, ornate palace, painterly renaissance light, regal composure'),
    creditCost: 4,
  },

  // === Sci-Fi (5) ===
  {
    id: 'scifi-astronaut',
    category: 'Sci-Fi',
    name: 'Astronaut Portrait',
    description: '우주인 헬멧 컨셉의 SF 포트레이트',
    useCase: 'SF 커뮤니티, 아바타',
    riskLevel: 'safe',
    styleTags: ['우주인', 'SF', '우주'],
    outfit: 'white spacesuit',
    background: 'space station',
    lighting: 'cold blue space light',
    expression: 'curious explorer gaze',
    defaultAspect: '1:1',
    defaultCreativity: 80,
    thumbnailPrompt: buildThumb('white spacesuit, space station, cold blue space light, curious explorer gaze'),
    promptSeed: buildSeed('SF/우주', 'Astronaut Portrait', 'white spacesuit, space station, cold blue space light, curious explorer gaze'),
    creditCost: 4,
  },
  {
    id: 'scifi-cyberpunk-executive',
    category: 'Sci-Fi',
    name: 'Cyberpunk Executive',
    description: '사이버펑크 거리의 임원 풍 SF 포트레이트',
    useCase: 'SF 커뮤니티, 크리에이터',
    riskLevel: 'safe',
    styleTags: ['사이버펑크', '임원', '네온'],
    outfit: 'futuristic business suit',
    background: 'cyberpunk megacity',
    lighting: 'neon rim light',
    expression: 'cold executive gaze',
    defaultAspect: '4:5',
    defaultCreativity: 80,
    thumbnailPrompt: buildThumb('futuristic business suit, cyberpunk megacity, neon rim light, cold executive gaze'),
    promptSeed: buildSeed('SF/사이버펑크', 'Cyberpunk Executive', 'futuristic business suit, cyberpunk megacity, neon rim light, cold executive gaze'),
    creditCost: 4,
  },
  {
    id: 'scifi-robot-engineer',
    category: 'Sci-Fi',
    name: 'Robot Engineer',
    description: '로봇 엔지니어 컨셉의 SF 테크 포트레이트',
    useCase: 'SF, 테크 커뮤니티',
    riskLevel: 'safe',
    styleTags: ['로봇', '엔지니어', '테크'],
    outfit: 'tech workshop wear',
    background: 'robot workshop',
    lighting: 'workshop ambient light',
    expression: 'focused engineer look',
    defaultAspect: '4:5',
    defaultCreativity: 80,
    thumbnailPrompt: buildThumb('tech workshop wear, robot workshop, workshop ambient light, focused engineer look'),
    promptSeed: buildSeed('SF/테크', 'Robot Engineer', 'tech workshop wear, robot workshop, workshop ambient light, focused engineer look'),
    creditCost: 4,
  },
  {
    id: 'scifi-mars-colonist',
    category: 'Sci-Fi',
    name: 'Mars Colonist',
    description: '화성 정착민 컨셉의 SF 포트레이트',
    useCase: 'SF 커뮤니티',
    riskLevel: 'safe',
    styleTags: ['화성', '정착민', 'SF'],
    outfit: 'mars colony suit',
    background: 'red mars desert',
    lighting: 'harsh mars sunlight',
    expression: 'pioneer determined gaze',
    defaultAspect: '4:5',
    defaultCreativity: 85,
    thumbnailPrompt: buildThumb('mars colony suit, red mars desert, harsh mars sunlight, pioneer determined gaze'),
    promptSeed: buildSeed('SF/화성', 'Mars Colonist', 'mars colony suit, red mars desert, harsh mars sunlight, pioneer determined gaze'),
    creditCost: 4,
  },
  {
    id: 'scifi-future-lab',
    category: 'Sci-Fi',
    name: 'Future Lab Scientist',
    description: '미래 연구소의 과학자 컨셉 SF 포트레이트',
    useCase: 'SF, 사이언스 커뮤니티',
    riskLevel: 'safe',
    styleTags: ['미래', '과학자', '연구소'],
    outfit: 'futuristic lab coat',
    background: 'futuristic lab',
    lighting: 'clean white lab light',
    expression: 'curious scientist look',
    defaultAspect: '4:5',
    defaultCreativity: 75,
    thumbnailPrompt: buildThumb('futuristic lab coat, futuristic lab, clean white lab light, curious scientist look'),
    promptSeed: buildSeed('SF/과학', 'Future Lab Scientist', 'futuristic lab coat, futuristic lab, clean white lab light, curious scientist look'),
    creditCost: 4,
  },

  // === Art / Avatar (5) ===
  {
    id: 'art-watercolor-portrait',
    category: 'Art/Avatar',
    name: 'Watercolor Portrait',
    description: '수채화 스타일의 아트 포트레이트',
    useCase: '아트 프로젝트, SNS',
    riskLevel: 'safe',
    styleTags: ['수채화', '아트', '파스텔'],
    outfit: 'soft watercolor attire',
    background: 'watercolor wash',
    lighting: 'soft painterly light',
    expression: 'gentle artistic gaze',
    defaultAspect: '1:1',
    defaultCreativity: 90,
    thumbnailPrompt: buildThumb('soft watercolor attire, watercolor wash background, soft painterly light, gentle artistic gaze, watercolor painting style'),
    promptSeed: buildSeed('아트/아바타', 'Watercolor Portrait', 'soft watercolor attire, watercolor wash, soft painterly light, gentle artistic gaze, watercolor painting style'),
    creditCost: 3,
  },
  {
    id: 'art-oil-painting',
    category: 'Art/Avatar',
    name: 'Oil Painting Portrait',
    description: '유화 스타일의 클래식 아트 포트레이트',
    useCase: '아트, 인테리어',
    riskLevel: 'safe',
    styleTags: ['유화', '클래식', '리얼리즘'],
    outfit: 'classic oil painting attire',
    background: 'dark oil canvas',
    lighting: 'chiaroscuro light',
    expression: 'timeless composure',
    defaultAspect: '4:5',
    defaultCreativity: 90,
    thumbnailPrompt: buildThumb('classic oil painting attire, dark oil canvas, chiaroscuro light, timeless composure, oil painting style'),
    promptSeed: buildSeed('아트/아바타', 'Oil Painting Portrait', 'classic oil painting attire, dark oil canvas, chiaroscuro light, timeless composure, oil painting style'),
    creditCost: 3,
  },
  {
    id: 'art-pixar-3d',
    category: 'Art/Avatar',
    name: '3D Animation Avatar',
    description: '3D 애니메이션 스타일의 캐릭터 아바타',
    useCase: 'SNS, 게임 아바타',
    riskLevel: 'safe',
    styleTags: ['3D', '애니메이션', '캐릭터'],
    outfit: 'stylized casual',
    background: 'stylized 3D environment',
    lighting: 'soft 3D render light',
    expression: 'expressive animated smile',
    defaultAspect: '1:1',
    defaultCreativity: 95,
    thumbnailPrompt: buildThumb('stylized casual, stylized 3D environment, soft 3D render light, expressive animated smile, 3D animation style'),
    promptSeed: buildSeed('아트/아바타', '3D Animation Avatar', 'stylized casual, stylized 3D environment, soft 3D render light, expressive animated smile, 3D animation style'),
    creditCost: 3,
  },
  {
    id: 'art-minimal-line-art',
    category: 'Art/Avatar',
    name: 'Minimal Line Art',
    description: '미니멀 라인 아트 스타일의 추상 아바타',
    useCase: 'SNS, 아트',
    riskLevel: 'safe',
    styleTags: ['라인 아트', '미니멀', '추상'],
    outfit: 'implied minimal lines',
    background: 'plain white',
    lighting: 'flat',
    expression: 'minimal line features',
    defaultAspect: '1:1',
    defaultCreativity: 95,
    thumbnailPrompt: buildThumb('minimal line art portrait, plain white, flat, minimal line features, one line art style'),
    promptSeed: buildSeed('아트/아바타', 'Minimal Line Art', 'minimal line art portrait, plain white, flat, minimal line features, one line art style'),
    creditCost: 3,
  },
  {
    id: 'art-pop-art',
    category: 'Art/Avatar',
    name: 'Pop Art Avatar',
    description: '팝 아트 스타일의 강렬한 컬러 아바타',
    useCase: 'SNS, 크리에이터',
    riskLevel: 'safe',
    styleTags: ['팝 아트', '강렬한 컬러', '코믹'],
    outfit: 'pop art style outfit',
    background: 'halftone pop pattern',
    lighting: 'flat pop art color',
    expression: 'dramatic pop art expression',
    defaultAspect: '1:1',
    defaultCreativity: 95,
    thumbnailPrompt: buildThumb('pop art style outfit, halftone pop pattern, flat pop art color, dramatic pop art expression, pop art style'),
    promptSeed: buildSeed('아트/아바타', 'Pop Art Avatar', 'pop art style outfit, halftone pop pattern, flat pop art color, dramatic pop art expression, pop art style'),
    creditCost: 3,
  },

  {
    id: 'anime-monster-partner-adventurer',
    category: 'Cosplay',
    name: 'Monster Partner Adventurer',
    description: '오리지널 몬스터 파트너 모험 애니메이션 감성의 전신/반전신 프로필',
    useCase: '코스프레 프로필, 팬덤풍 아바타, 모험 콘셉트',
    riskLevel: 'notice',
    styleTags: ['모험가', '파트너 몬스터', '애니메이션 감성'],
    outfit: 'adventure goggles-inspired headwear, layered camp jacket, fingerless travel gloves, compact backpack',
    background: 'bright summer adventure field with abstract digital sparkle atmosphere',
    lighting: 'warm daylight with optimistic rim light',
    expression: 'energetic expedition smile',
    defaultAspect: '4:5',
    composition: 'three-quarter',
    inspirationPolicy: 'inspired-original',
    estimatedComplexity: 'very-complex',
    defaultCreativity: 85,
    thumbnailPrompt: buildThumb('generic fictional adult adventure anime hero, goggles-inspired travel outfit, small original companion-creature silhouette blurred in background, bright summer adventure field, warm daylight, no franchise logo, no recognizable mascot'),
    promptSeed: buildSeed('코스프레/팬덤풍 프로필', 'Monster Partner Adventurer', 'original monster-partner adventure anime inspired travel outfit, bright summer adventure field, warm daylight, energetic expedition smile'),
    creditCost: 3,
  },
  {
    id: 'anime-stadium-trainer',
    category: 'Cosplay',
    name: 'Creature Trainer Stadium',
    description: '오리지널 몬스터 트레이너 주인공풍 스타디움 전신 프로필',
    useCase: '팬덤풍 아바타, 스포츠 어드벤처 프로필',
    riskLevel: 'notice',
    styleTags: ['트레이너', '스타디움', '전신 포즈'],
    outfit: 'sporty travel jacket, simple cap-like silhouette, backpack strap, clean sneakers',
    background: 'bright outdoor arena and adventure route stadium',
    lighting: 'dramatic sunlight and clean rim light',
    expression: 'confident champion expression',
    defaultAspect: '4:5',
    composition: 'full-body',
    inspirationPolicy: 'inspired-original',
    estimatedComplexity: 'very-complex',
    defaultCreativity: 85,
    thumbnailPrompt: buildThumb('generic fictional adult creature trainer, sporty travel jacket, simple cap-like silhouette, backpack strap, bright outdoor arena, full-body confident pose, no franchise logo, no mascot creature'),
    promptSeed: buildSeed('코스프레/팬덤풍 프로필', 'Creature Trainer Stadium', 'original creature-trainer adventure protagonist styling, bright outdoor arena, dramatic sunlight, confident full-body champion pose'),
    creditCost: 3,
  },
  {
    id: 'fantasy-wizard-school',
    category: 'Fantasy',
    name: 'Wizard School Student',
    description: '마법학교 학생 분위기의 오리지널 판타지 프로필',
    useCase: '판타지 프로필, 코스프레, 게임 아바타',
    riskLevel: 'notice',
    styleTags: ['마법학교', '로브', '도서관'],
    outfit: 'tailored robe-like academic coat, layered neutral scarf, wand-like prop',
    background: 'candlelit stone library and grand study hall',
    lighting: 'warm magical rim light with floating dust motes',
    expression: 'curious intelligent expression',
    defaultAspect: '4:5',
    composition: 'three-quarter',
    inspirationPolicy: 'inspired-original',
    estimatedComplexity: 'complex',
    defaultCreativity: 80,
    thumbnailPrompt: buildThumb('generic fictional adult wizard school student, tailored robe-like academic coat, candlelit stone library, wand-like prop, warm magical rim light, no school crest, no franchise symbols'),
    promptSeed: buildSeed('판타지/마법학교 프로필', 'Wizard School Student', 'original wizard-school student styling, candlelit stone library, warm magical rim light, curious intelligent expression'),
    creditCost: 3,
  },
  {
    id: 'fantasy-arcane-professor',
    category: 'Fantasy',
    name: 'Arcane Professor',
    description: '고대 도서관의 아케인 교수 같은 판타지 프로필',
    useCase: '판타지 프로필, 작가/크리에이터 아바타',
    riskLevel: 'safe',
    styleTags: ['아케인', '교수', '고대 도서관'],
    outfit: 'long tailored academic coat with refined layered fabric',
    background: 'ancient library with floating books and arcane diagrams',
    lighting: 'warm candlelight mixed with cool moonlight',
    expression: 'thoughtful mentor expression',
    defaultAspect: '4:5',
    composition: 'three-quarter',
    inspirationPolicy: 'original',
    estimatedComplexity: 'complex',
    defaultCreativity: 80,
    thumbnailPrompt: buildThumb('arcane professor, long tailored academic coat, ancient library with floating books, warm candlelight and cool moonlight, thoughtful mentor expression'),
    promptSeed: buildSeed('판타지 프로필', 'Arcane Professor', 'long tailored academic coat, ancient library with floating books, warm candlelight and cool moonlight, thoughtful mentor expression'),
    creditCost: 3,
  },
  {
    id: 'wedding-full-shot-classic',
    category: 'Editorial',
    name: 'Classic Wedding Full Shot',
    description: '플로럴 아치와 부드러운 자연광의 클래식 웨딩 전신 프로필',
    useCase: '웨딩 콘셉트, 커플/개인 화보, 이벤트 프로필',
    riskLevel: 'safe',
    styleTags: ['웨딩', '전신', '플로럴'],
    outfit: 'formal wedding attire suited to the subject, refined suit or wedding dress styling',
    background: 'floral arch and soft daylight wedding venue',
    lighting: 'soft natural daylight',
    expression: 'romantic dignified expression',
    defaultAspect: '4:5',
    composition: 'full-body',
    inspirationPolicy: 'original',
    estimatedComplexity: 'complex',
    defaultCreativity: 55,
    thumbnailPrompt: buildThumb('classic wedding full-body portrait, formal wedding attire, floral arch, soft daylight venue, romantic dignified expression, premium wedding photography'),
    promptSeed: buildSeed('웨딩 콘셉트', 'Classic Wedding Full Shot', 'formal wedding attire, floral arch and soft daylight venue, romantic dignified expression, full-body wedding photography'),
    creditCost: 3,
  },
  {
    id: 'wedding-night-garden-full-shot',
    category: 'Editorial',
    name: 'Night Garden Wedding Full Shot',
    description: '정원 조명과 시네마틱 무드의 나이트 웨딩 전신 프로필',
    useCase: '웨딩 콘셉트, 이벤트 화보',
    riskLevel: 'safe',
    styleTags: ['나이트 웨딩', '정원', '전신'],
    outfit: 'formal evening wedding attire',
    background: 'night garden with warm bokeh lanterns and floral path',
    lighting: 'dark emerald and gold cinematic rim light',
    expression: 'romantic confident expression',
    defaultAspect: '4:5',
    composition: 'full-body',
    inspirationPolicy: 'original',
    estimatedComplexity: 'complex',
    defaultCreativity: 60,
    thumbnailPrompt: buildThumb('night garden wedding full-body portrait, formal evening wedding attire, warm bokeh lanterns, floral path, cinematic gold rim light'),
    promptSeed: buildSeed('웨딩 콘셉트', 'Night Garden Wedding Full Shot', 'formal evening wedding attire, night garden with warm lantern bokeh, romantic confident expression, full-body cinematic portrait'),
    creditCost: 3,
  },
  {
    id: 'sports-football-player-full-shot',
    category: 'Creator',
    name: 'Football Player Full Shot',
    description: '로고 없는 유니폼과 경기장 배경의 축구선수 전신 프로필',
    useCase: '스포츠 프로필, 팬 포스터, SNS',
    riskLevel: 'safe',
    styleTags: ['축구', '전신', '스타디움'],
    outfit: 'generic football kit with no club or national team logo',
    background: 'stadium pitch or tunnel entrance',
    lighting: 'dramatic stadium lights',
    expression: 'confident focused expression',
    defaultAspect: '4:5',
    composition: 'full-body',
    inspirationPolicy: 'original',
    estimatedComplexity: 'complex',
    defaultCreativity: 65,
    thumbnailPrompt: buildThumb('football athlete full-body profile, generic logo-free kit, stadium pitch, ball prop near foot, dramatic stadium lights, confident focused expression'),
    promptSeed: buildSeed('스포츠 프로필', 'Football Player Full Shot', 'generic football kit, stadium pitch or tunnel entrance, dramatic stadium lights, confident focused full-body athlete stance'),
    creditCost: 3,
  },
  {
    id: 'sports-football-captain-poster',
    category: 'Creator',
    name: 'Football Captain Poster',
    description: '캡틴 포스터 스타일의 축구 전신 콘셉트',
    useCase: '스포츠 포스터, SNS 프로필',
    riskLevel: 'safe',
    styleTags: ['축구 캡틴', '포스터', '전신'],
    outfit: 'generic captain-style sports uniform with no logos',
    background: 'misty stadium tunnel and floodlights',
    lighting: 'cinematic rim lighting',
    expression: 'strong leadership expression',
    defaultAspect: '4:5',
    composition: 'full-body',
    inspirationPolicy: 'original',
    estimatedComplexity: 'complex',
    defaultCreativity: 70,
    thumbnailPrompt: buildThumb('football captain full-body poster, generic sports uniform, misty stadium tunnel, floodlights, cinematic rim lighting, strong leadership expression, no logos'),
    promptSeed: buildSeed('스포츠 포스터', 'Football Captain Poster', 'generic captain-style sports uniform, misty stadium tunnel, cinematic rim lighting, heroic full-body leadership pose'),
    creditCost: 3,
  },
  {
    id: 'idol-stage-full-shot',
    category: 'Creator',
    name: 'Idol Stage Full Shot',
    description: 'LED 무대와 댄스 포즈의 아이돌 전신 프로필',
    useCase: '아이돌 콘셉트, 크리에이터 프로필, SNS',
    riskLevel: 'safe',
    styleTags: ['아이돌', '무대', '전신'],
    outfit: 'modern original performance outfit',
    background: 'LED concert stage with floor reflections',
    lighting: 'colorful concert lighting',
    expression: 'charismatic confident expression',
    defaultAspect: '4:5',
    composition: 'full-body',
    inspirationPolicy: 'original',
    estimatedComplexity: 'complex',
    defaultCreativity: 75,
    thumbnailPrompt: buildThumb('K-pop inspired idol stage full-body portrait, modern original performance outfit, LED concert stage, dance-ready pose, colorful concert lighting, no real group logo'),
    promptSeed: buildSeed('아이돌 콘셉트', 'Idol Stage Full Shot', 'modern original performance outfit, LED concert stage, colorful concert lighting, dance-ready full-body pose, charismatic confident expression'),
    creditCost: 3,
  },
  {
    id: 'idol-album-jacket',
    category: 'Editorial',
    name: 'Idol Album Jacket',
    description: '앨범 재킷처럼 연출된 엔터테인먼트 화보 프로필',
    useCase: '아이돌 콘셉트, 앨범 재킷풍 프로필',
    riskLevel: 'safe',
    styleTags: ['앨범 재킷', '스튜디오', '엔터테인먼트'],
    outfit: 'fashion-forward entertainment styling',
    background: 'glossy studio set with soft neon or pastel backdrop',
    lighting: 'controlled beauty lighting',
    expression: 'confident album-jacket gaze',
    defaultAspect: '4:5',
    composition: 'three-quarter',
    inspirationPolicy: 'original',
    estimatedComplexity: 'complex',
    defaultCreativity: 75,
    thumbnailPrompt: buildThumb('idol album-jacket editorial portrait, fashion-forward styling, glossy studio set, soft neon pastel backdrop, controlled beauty lighting, confident gaze'),
    promptSeed: buildSeed('아이돌 콘셉트', 'Idol Album Jacket', 'fashion-forward entertainment styling, glossy studio set with neon pastel backdrop, controlled beauty lighting, confident album-jacket gaze'),
    creditCost: 3,
  },
  {
    id: 'model-runway-full-shot',
    category: 'Editorial',
    name: 'Runway Model Full Shot',
    description: '런웨이 조명과 하이패션 실루엣의 모델 전신 프로필',
    useCase: '모델 프로필, 패션 화보, 포트폴리오',
    riskLevel: 'safe',
    styleTags: ['런웨이', '모델', '전신'],
    outfit: 'original designer-inspired black or neutral statement outfit with no brand logo',
    background: 'runway with dramatic fashion lights',
    lighting: 'dramatic runway shadows and low-angle fashion light',
    expression: 'calm high-fashion model gaze',
    defaultAspect: '4:5',
    composition: 'full-body',
    inspirationPolicy: 'original',
    estimatedComplexity: 'complex',
    defaultCreativity: 75,
    thumbnailPrompt: buildThumb('high-fashion runway model full-body portrait, original designer-inspired neutral outfit, catwalk pose, runway lights, dramatic shadows, luxury editorial look'),
    promptSeed: buildSeed('모델/패션 프로필', 'Runway Model Full Shot', 'designer-inspired neutral statement outfit, runway lights, dramatic shadows, full-body catwalk pose, luxury editorial look'),
    creditCost: 3,
  },
  {
    id: 'model-lookbook-editorial',
    category: 'Editorial',
    name: 'Lookbook Editorial Model',
    description: '깔끔한 스튜디오의 룩북 모델 화보 프로필',
    useCase: '모델 프로필, 룩북, 패션 포트폴리오',
    riskLevel: 'safe',
    styleTags: ['룩북', '패션', '전신'],
    outfit: 'curated layered fashion outfit with no logos',
    background: 'clean studio or architectural backdrop',
    lighting: 'high-end catalog lighting',
    expression: 'calm modern model expression',
    defaultAspect: '4:5',
    composition: 'full-body',
    inspirationPolicy: 'original',
    estimatedComplexity: 'standard',
    defaultCreativity: 65,
    thumbnailPrompt: buildThumb('premium fashion lookbook full-body editorial portrait, curated layered outfit, clean studio backdrop, off-center composition, calm model expression'),
    promptSeed: buildSeed('모델/패션 프로필', 'Lookbook Editorial Model', 'curated layered fashion outfit, clean studio or architectural backdrop, high-end catalog lighting, full-body lookbook pose'),
    creditCost: 3,
  },
]

export const CATEGORY_LABELS: Record<ConceptCategory, string> = {
  Professional: '프로페셔널',
  Social: '소셜/라이프스타일',
  'ID-style': '증명사진 스타일',
  Editorial: '에디토리얼',
  Creator: '크리에이터',
  Cosplay: '코스프레',
  Fantasy: '판타지',
  'Sci-Fi': 'SF',
  'Art/Avatar': '아트/아바타',
}

export const CATEGORY_ORDER: ConceptCategory[] = [
  'Professional',
  'Social',
  'ID-style',
  'Editorial',
  'Creator',
  'Cosplay',
  'Fantasy',
  'Sci-Fi',
  'Art/Avatar',
]

export const getConceptById = (id: string): Concept | undefined =>
  CONCEPTS.find((c) => c.id === id)

export const getConceptsByCategory = (category: ConceptCategory): Concept[] =>
  CONCEPTS.filter((c) => c.category === category)
